<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5Lit5paH');
$cfg_Cs[2]=array(0,1,1,'RW5nbGlzaA==');
$cfg_Cs[3]=array(1,1,1,'5YWJ5qCF5p2/5Y6C5a625LuL57uN');
$cfg_Cs[4]=array(1,1,1,'5YWJ5qCF5p2/5Lqn5ZOB5LuL57uN');
$cfg_Cs[5]=array(1,1,1,'5YWJ5qCF5p2/6IGU57O75pa55byP');
$cfg_Cs[6]=array(2,1,1,'QWJvdXQgbGVudGljdWxhcg==');
$cfg_Cs[7]=array(2,1,1,'bGVudGljdWxhciBwcm9kdWN0');
$cfg_Cs[8]=array(2,1,1,'Q29udGFjdCBsZW50aWN1bGFy');
$cfg_Cs[9]=array(1,1,1,'5bm754Gv54mH');
$cfg_Cs[10]=array(2,1,1,'QmFubmVy');
$cfg_Cs[11]=array(1,1,1,'5YWJ5qCF5p2/5oqA5pyv5pSv5oyB');
$cfg_Cs[12]=array(2,1,1,'TGVudGljdWxhciBUZWNoLg==');
?>