
<m:item name='基本设置' link='cjx.php?ac=setting' rank='' target='main' />
<m:item name='高级设置' link='cjx.php?ac=advanced' rank='' target='main' />
<m:item name='伪原创设置' link='cjx.php?ac=seo' rank='' target='main' />
<m:item name='搜索优化设置' link='cjx.php?ac=search' rank='' target='main' />
<m:item name='采集任务' link='cjx.php?ac=task' rank='' target='main' />
<m:item name='超级采集' link='cjx.php?ac=advcjx' rank='' target='main' />
<m:item name='在线更新' link='cjx.php?ac=update' rank='' target='main' />
<m:item name='发现' link='cjx.php?ac=explore' rank='' target='main' />
<m:item name='帮助中心' link='//www.caijixia.cn/Related/?plugin=caijixia' rank='' target='main' />
