<?php
$z[0]=Array("global","",105,132);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",162,189);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",302,329);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",344,376);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("channel","\r\n<li><a class=\"hide\" href=\"[field:typelink/]\">[field:typename/]</a>\r\n</li>",703,830);
$z[4][4]['row']="4";
$z[4][4]['typeid']="2";

?>