<?php
$z[0]=Array("global","",39,71);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",280,307);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",346,373);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",486,513);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",525,557);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",875,902);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",910,938);
$z[6][4]['name']="cfg_indexname";
$z[7]=Array("channel","\r\n<li><a class=\"hide\" href=\"[field:typelink/]\">[field:typename/]</a>\r\n</li>",953,1080);
$z[7][4]['row']="4";
$z[7][4]['typeid']="1";

?>